spring:
  application:
    name: dynamic-captcha
  webflux:
    base-path: /
  netty:
    leak-detection: PARANOID

management:
  endpoint.health.show-details: always
  endpoints.web.exposure:
    include: '*'
    exclude: 'shutdown'

logging:
  level:
    root: INFO